- include_vars: ../../vars.yml
- name: moitor packages installed
  apt: name={{ '{{ item }}' }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - nagios-nrpe-server
    - nagios-plugins

# TODO: For each server, ip from config?
- name: monitor server allowed
  lineinfile:
    dest: /etc/nagios/nrpe.cfg
    regexp: ^allowed_hosts
    line: allowed_hosts=78.211.216.22

- name: nrpe reloaded
  service: name=nagios-nrpe-server state=reloaded
