- name: ({{ __model_name__ }}) {{ __service_name__ }} mysql user privilege
  mysql_user:
    name: {{ mysql_user_name }}
    host: "{{ "{{ item }}" }}"
    password: "{{ mysql_user_password }}"
    login_user: root
    login_password: "{{ MYSQL_USER_ROOT_PASSWORD }}"
    check_implicit_admin: yes
    priv: "{{ mysql_database }}.*:ALL,GRANT"
  with_items:
    - "{{ "{{ inventory_hostname }}" }}"
    - 127.0.0.1
    - ::1
    - localhost
