- name: ({{ __model_name__ }}) {{ __service_name__ }} mysql database
  mysql_db:
    name: {{ mysql_database }}
    state: present
    login_user: root
    login_password: "{{ MYSQL_USER_ROOT_PASSWORD }}"

- name: ({{ __model_name__ }}) {{ __service_name__ }} mysql user privilege
  mysql_user:
    name: {{ mysql_user_name }}
    host: "{{ "{{ item }}" }}"
    password: "{{ mysql_user_password }}"
    login_user: root
    login_password: "{{ MYSQL_USER_ROOT_PASSWORD }}"
    check_implicit_admin: yes
    priv: "{{ mysql_database }}.*:ALL,GRANT"
  with_items:
    - "{{ "{{ inventory_hostname }}" }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: ({{ __model_name__ }}) {{ __service_name__ }} source directory
  file: path=/srv/www/{{ domain }}/www state=directory owner=www-data group=www-data mode=0775 recurse=yes

- name: ({{ __model_name__ }}) {{ __service_name__ }}  vhost
  copy: src=../../files/services/lamp_website/{{ __service_name_slug__ }}/{{ domain }}.conf dest=/etc/apache2/sites-available/{{ domain }}.conf mode=0644

- name: ({{ __model_name__ }}) {{ __service_name__ }}  vhost enabled
  file: src=/etc/apache2/sites-available/{{ domain }}.conf dest=/etc/apache2/sites-enabled/{{ domain }}.conf state=link

- name: ({{ __model_name__ }}) {{ __service_name__ }} apache reloaded
  service: name=apache2 state=reloaded
