- name: ({{ __service_name__ }}) {{ __service_name__ }} mysql user privilege
  mysql_user:
    name: {{ __service_name__ }}
    host: "{{ "{{ item }}" }}"
    password: "{{ MYSQL_USER_ROOT_PASSWORD }}"
    login_user: {{ mysql_user_name }}
    login_password: "{{ mysql_user_password }}"
    check_implicit_admin: yes
    priv: "{{ mysql_database }}.*:ALL,GRANT"
  with_items:
    - "{{ "{{ inventory_hostname }}" }}"
    - 127.0.0.1
    - ::1
    - localhost
