- name: ansible nagios services file
  lineinfile:
    dest: /usr/local/nagios/etc/nagios.cfg
    line: cfg_file=/usr/local/nagios/etc/objects/ansible.cfg

- name: nagios ansible.cfg file exist
  file:
    path: /usr/local/nagios/etc/objects/ansible.cfg
    owner: root
    group: nagios
    mode: 0644
    state: touch

- name: nagios target service host declared
  blockinfile:
    dest: /usr/local/nagios/etc/objects/ansible.cfg
    marker: "### {mark} ANSIBLE MANAGED BLOCK (target host definition) ###"
    content: |
      define host {
        use generic-host
        host_name {{ host_name }}
        alias {{ host_name }} (ansible managed)
        address {{ target_ip }}
        max_check_attempts 1
      }

# TODO: file age configured
- name: {{ __service_name__ }} backup db check
  blockinfile:
    dest: /usr/local/nagios/etc/objects/ansible.cfg
    marker: "### {mark} ANSIBLE MANAGED BLOCK ({{ __service_name__ }} backup db check definition) ###"
    content: |
      define service{
        use local-service
        host_name {{ backup_host_name }}
        service_description {{ __service_name__ }} db backup check
        check_command check_nrpe!check_file_age -a 691200 791200 "{{ last_db_file_path }}"
        notifications_enabled 1
      }

# TODO: file age configured
- name: {{ __service_name__ }} backup files check check
  blockinfile:
    dest: /usr/local/nagios/etc/objects/ansible.cfg
    marker: "### {mark} ANSIBLE MANAGED BLOCK ({{ __service_name__ }} files backup check definition) ###"
    content: |
      define service{
        use local-service
        host_name {{ backup_host_name }}
        service_description {{ __service_name__ }} files backup check
        check_command check_nrpe!check_file_age -a 691200 791200 "{{ last_files_file_path }}"
        notifications_enabled 1
      }

# TODO: Check backups ?
# TODO: Checks standarts CPU etc definis ailleurs

- name: nagios reloaded
  service: name=nagios state=reloaded
