- name: backup packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - rsync

- name: backup user
  user: name=backup comment="Backup user" shell=/bin/bash home=/home/backup

- name: backup user key
  copy: src=../../../../keys/id_rsa_backup dest=/home/backup/.ssh/id_rsa mode=0600 owner=backup # TODO: parameter + copy into builds

- name: backup user key
  copy: src=../../../../keys/id_rsa_backup.pub dest=/home/backup/.ssh/id_rsa.pub mode=0600 owner=backup # TODO: parameter + copy into builds

- name: Prevent ssh password login of backup user
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "### {mark} ANSIBLE MANAGED BLOCK (backup user) ###"
    content: |
      Match user backup
        PasswordAuthentication no
