- name: packages installed
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=0
  with_items:
    - fail2ban

- name: fail2ban jail.local
  template: src=../../files/groups/web/jail.local dest=/etc/fail2ban/jail.local mode=0664

- name: fail2ban ssh.conf
  template: src=../../files/groups/web/ssh.conf dest=/etc/fail2ban/jail.d/ssh.conf mode=0664

- name: fail2ban ssh-ddos.conf
  template: src=../../files/groups/web/ssh-ddos.conf dest=/etc/fail2ban/jail.d/ssh-ddos.conf mode=0664

- name: fail2ban reloaded
  service: name=fail2ban state=restarted

- name: Prevent ssh password login of ansible user
  blockinfile:
    dest: /etc/ssh/sshd_config
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK (ansible user) -->"
    content: |
      Match user ansible
        PasswordAuthentication no
