---
- hosts: web
  tasks:
    - include_vars: ../vars.yml
    - name: packages installed
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
      with_items:
        - fail2ban
