---
- hosts: lamp
  tasks:
    - name: debconf for pma
      debconf: name=phpmyadmin question='phpmyadmin/dbconfig-install' value='true' vtype='boolean'

    - name: debconf for pma
      debconf: name=phpmyadmin question='phpmyadmin/app-password-confirm' value='PASSWORD' vtype='password'

    - name: debconf for pma
      debconf: name=phpmyadmin question='phpmyadmin/mysql/admin-pass' value='PASSWORD_PMA' vtype='password'

    - name: debconf for pma
      debconf: name=phpmyadmin question='phpmyadmin/mysql/app-pass' value='PASSWORD_PMA' vtype='password'

    - name: debconf for pma
      debconf: name=phpmyadmin question='phpmyadmin/reconfigure-webserver' value='' vtype='multiselect'

    - name: packages installed
      apt: name={{ item }} state=present update_cache=yes cache_valid_time=86400
      with_items:
        - mysql-server
        - apache2
        - libapache2-mod-php5
        - python-mysqldb
        - python-passlib
        - phpmyadmin

    - name: mysql root privileges
      mysql_user:
        name: root
        host: "{{ item }}"
        password: "PASSWORD"
        login_user: root
        login_password: "PASSWORD"
        check_implicit_admin: yes
        priv: "*.*:ALL,GRANT"
      with_items:
      - "{{ inventory_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

    - name: install phpmyadmin
      apt: name=phpmyadmin state=present update_cache=yes cache_valid_time=86400

    - name: services up
      service: name={{ item }} state=running enabled=yes
      with_items:
        - apache2
        - mysql

    - name: Hello World PHP script
      copy: src=web/index.php dest=/var/www/index.php mode=0664

    - name: pma virtual host
      copy: src=web/phpmyadmin.conf dest=/etc/apache2/conf.d/phpmyadmin.conf mode=0664

    - name: apache reloaded
      service: name=apache2 state=reloaded

    - name: secure pma http access
      htpasswd: path=/etc/htaccess/pma name=root password=PASSWORD owner=root group=www-data mode=0640 state=present
